name: Leanplum Automation Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'
    
jobs:
  build-and-test:
  
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4444:4444
        options: --shm-size="2g"
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml
    - name: Run Features
      run: mvn clean test -Duser.email=${{ secrets.EMAIL }} -Duser.password=${{ secrets.PASSWORD }}
    - name: Upload Test Results
      uses: actions/upload-artifact@v3.1.0
      with:
        name: test-results
        path: ./target/cucumber-report
